import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ballers Gear Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header>
        <div className="header-usuario">
          <img src="/logoballersgearzone.jpg" alt="Ballers Gear Zone Logo" className="logo" />
          <h1 className="titulo-header">Ballers Gear Zone</h1>
          <img src="/mapanba.jpg" alt="Mapa Nba" className="mapa" />
</div>
      </header>
        {children}
      
        <footer style={{ backgroundColor: 'black', color: 'white', padding: '20px', marginTop:'100px', width:"100%", height:"480px"}}>
          <div style={{ display: 'flex', justifyContent: 'space-around', flexWrap: 'wrap' }}>
            {/* Contacto */}
            <div style={{ flex: 1, minWidth: '200px', margin: '10px' }}>
              <h3 style={{ marginBottom: '10px' }}>Contacto</h3>
              <a href="https://www.google.com/intl/es-419/gmail/about/"> <img src="/gmail.png" alt=""  className="gmail"/> Gmail: ballersgearzone@gmail.com</a><br></br><br></br>
              <a href="https://web.whatsapp.com"> <img src="/telefono.png" alt=""  className="telefono"/> Teléfono: 2284575131</a><br></br><br></br>
              <a href="https://www.google.com/maps/place/Olavarría,+Provincia+de+Buenos+Aires/@-36.859582,-60.3696013,12z/data=!3m1!4b1!4m6!3m5!1s0x959445daae9e90a3:0xd11aadb313dbf072!8m2!3d-36.8937167!4d-60.3233499!16zL20vMGJfeTl5?entry=ttu"> <img src="/localidad.png" alt=""  className="localidad"/> Localidad: Olavarria</a><br></br><br></br>
              <a href="https://www.google.com/maps/place/Dorrego+2584,+B7400+Olavarría,+Provincia+de+Buenos+Aires/@-36.8910858,-60.3253,17z/data=!3m1!4b1!4m5!3m4!1s0x959445c6c1635785:0xb65d0f0c2ae7c80d!8m2!3d-36.8910858!4d-60.3227197?entry=ttu"> <img src="/direccion.avif" alt=""  className="direccion" />  Dirección: Dorrego 2584</a><br></br><br></br>
              <a href="https://www.instagram.com"> <img src="/instagram.png" alt="" className="instagram"/> Instagram: Ballersgearzoneolav</a>
            </div>

            {/* Información */}
            <div style={{ flex: 1, minWidth: '200px', margin: '10px' }}>
              <h3 style={{ marginBottom: '10px' }}>Información</h3>
              <ul style={{ listStyleType: 'none', padding: 0 }}>
                <li><a href="/" style={{ color: 'white', textDecoration: 'none' }}>Sobre Nosotros</a></li>
                <li><a href="" style={{ color: 'white', textDecoration: 'none' }}>Envíos a todo el país</a></li>
                <li><a href="" style={{ color: 'white', textDecoration: 'none' }}>Política de Privacidad</a></li>
                <li><a href="" style={{ color: 'white', textDecoration: 'none' }}>Términos y Condiciones</a></li>
              </ul>
            </div>
          </div>

          {/* Copyright */}
          <div style={{ textAlign: 'center', marginTop: '20px' }}>
            <p>&copy; 2024 Ballersgearzone. Todos los derechos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
