import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ballers Gear Zone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header>
        <div className="header-usuario">
          <img src="logoballersgearzone.jpg" alt="Ballers Gear Zone Logo" className="logo" />
          <h1 className="titulo-header">Ballers Gear Zone</h1>
          <img src="mapanba.jpg" alt="Mapa Nba" className="mapa" />
</div>
      </header>
        {children}
      
        <footer style={{ backgroundColor: 'black', color: 'white', padding: '20px', marginTop:'100px', width:"100%", height:"470px"}}>
          <div style={{ display: 'flex', justifyContent: 'space-around', flexWrap: 'wrap' }}>
            {/* Contacto */}
            <div style={{ flex: 1, minWidth: '200px', margin: '10px' }}>
              <h3 style={{ marginBottom: '10px' }}>Contacto</h3>
              <p> <img src="gmail.png" alt=""  className="gmail"/> Gmail: ballersgearzone@gmail.com</p>
              <p> <img src="telefono.png" alt=""  className="telefono"/> Teléfono: 2284575131</p>
              <p> <img src="localidad.png" alt=""  className="localidad"/> Localidad: Olavarria</p>
              <p> <img src="direccion.avif" alt=""  className="direccion"/>  Dirección: Velez Sarsfield 3831</p>
              <p> <img src="instagram.png" alt=""  className="instagram"/> Instagram: Ballersgearzoneolav</p>
            </div>

            {/* Información */}
            <div style={{ flex: 1, minWidth: '200px', margin: '10px' }}>
              <h3 style={{ marginBottom: '10px' }}>Información</h3>
              <ul style={{ listStyleType: 'none', padding: 0 }}>
                <li><a href="/" style={{ color: 'white', textDecoration: 'none' }}>Sobre Nosotros</a></li>
                <li><a href="" style={{ color: 'white', textDecoration: 'none' }}>Envíos a todo el país</a></li>
                <li><a href="" style={{ color: 'white', textDecoration: 'none' }}>Política de Privacidad</a></li>
                <li><a href="" style={{ color: 'white', textDecoration: 'none' }}>Términos y Condiciones</a></li>
              </ul>
            </div>
          </div>

          {/* Copyright */}
          <div style={{ textAlign: 'center', marginTop: '20px' }}>
            <p>&copy; 2024 Ballersgearzone. Todos los derechos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
